# Generated by Django 4.1.7 on 2024-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='name',
        ),
        migrations.AddField(
            model_name='personne',
            name='password',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='username',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
